apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  creationTimestamp: 2017-06-14T14:19:07Z
  labels:
    app: jme-apache-test
  name: jme-apache-test
  namespace: jme-test
  resourceVersion: "8919129"
  selfLink: /oapi/v1/namespaces/jme-test/buildconfigs/jme-apache-test
  uid: 6d9a3587-510c-11e7-a9bd-0050568690d8
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: jme-apache-test:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: httpd-24-rhel7:latest
        namespace: openshift
    type: Source
  triggers:
  - github:
      secret: 91XVP1L6LQt8Gg6D68i_
    type: GitHub
  - generic:
      secret: z7hCRzUDdn_plqgsyZQ5
    type: Generic
status:
  lastVersion: 1
