apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: 2017-06-14T14:21:01Z
  generation: 4
  labels:
    app: jme-apache-test
  name: jme-apache-test
  namespace: jme-test
  resourceVersion: "8920461"
  selfLink: /oapi/v1/namespaces/jme-test/deploymentconfigs/jme-apache-test
  uid: b143ba34-510c-11e7-a9bd-0050568690d8
spec:
  replicas: 1
  selector:
    app: jme-apache-test
    deploymentconfig: jme-apache-test
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/container.jme-apache-test.image.entrypoint: '["container-entrypoint","/usr/libexec/s2i/run"]'
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: jme-apache-test
        deploymentconfig: jme-apache-test
    spec:
      containers:
      - image: 10.20.19.139:5000/jme-test/jme-apache-test@sha256:d73595fcc1c76f461cf7ceafee870d4178022089e5c87f07c48f0442688b3f75
        imagePullPolicy: Always
        name: jme-apache-test
        ports:
        - containerPort: 8443
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        - containerPort: 80
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /var/log/httpd24
          name: jme-apache-test-volume-1
        - mountPath: /var/www
          name: jme-apache-test-volume-2
        - mountPath: /mnt
          name: volume-bn1vw
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: jme-apache-test-volume-1
      - emptyDir: {}
        name: jme-apache-test-volume-2
      - name: volume-bn1vw
        persistentVolumeClaim:
          claimName: jme-apache-test
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - jme-apache-test
      from:
        kind: ImageStreamTag
        name: jme-apache-test:latest
        namespace: jme-test
      lastTriggeredImage: 10.20.19.139:5000/jme-test/jme-apache-test@sha256:d73595fcc1c76f461cf7ceafee870d4178022089e5c87f07c48f0442688b3f75
    type: ImageChange
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2017-06-14T14:29:42Z
    message: Replication controller "jme-apache-test-2" has completed progressing
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: 2017-06-14T14:30:53Z
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  details:
    causes:
    - type: ConfigChange
    message: config change
  latestVersion: 2
  observedGeneration: 4
  replicas: 1
  updatedReplicas: 1
